# ProTrades Configuration File
# Streamlined configuration for trading system

# Debug mode for detailed logging
debug: false

# Plugin version info
version: "1.0.0"

# Database settings (future expansion)
database:
  enabled: false
  type: "sqlite"
  
# Trade system settings
trades:
  auto-save: true
  save-interval: 300 # seconds
  backup-trades: true
  max-trades-per-gui: 54
  
# Performance settings
performance:
  cache-items: true
  cache-size: 1000
  async-operations: true
  
# Integration settings
integration:
  proitems: true
  vault: false
  placeholderapi: false

# ItemX Configuration (integrated and simplified)
itemx:
  # Debug mode
  debug: true
  
  # Message prefix
  prefix: "<gray>[<aqua>ProTrades</aqua>]</gray> "
  
  # Command messages
  messages:
    give-message: "<green>Gave <yellow>%item%</yellow> to <blue>%player%</blue>"
    get-message: "<green>You received <yellow>%item%</yellow>"
    get-category-message: "<green>You received <yellow>%count%</yellow> items from category <aqua>%category%</aqua>"
    no-permission: "<red>You don't have permission to use this command."
    player-not-found: "<red>Player <yellow>%player%</yellow> not found."
    item-not-found: "<red>Item <yellow>%item%</yellow> not found."
    reload-success: "<green>ProTrades has been reloaded successfully!"
    template-applied: "<green>Template <yellow>%template%</yellow> applied to GUI <aqua>%gui%</aqua>"
    trade-created: "<green>Trade <yellow>%trade%</yellow> created successfully!"
    config-saved: "<green>Configuration saved successfully!"
    
  # NBT Configuration
  nbt:
    key: "protrades:id"
    namespace-prefix: "protrades"
    
  # Item Configuration
  items:
    auto-reload: true
    reload-interval: 300 # seconds
    
  # Template Configuration
  templates:
    auto-load: true
    validate-items: true
    create-missing-items: false
    
  # GUI Configuration
  gui:
    default-title: "&1&lProTrades Shop"
    default-rows: 6
    fill-empty-slots: true
    fill-material: "GRAY_STAINED_GLASS_PANE"
    
# Example Configuration
examples:
  create-default-items: true
  create-default-trades: true
  create-default-templates: true