# ProTrades Configuration File
# Configuration for the trade system

# Debug mode for detailed logging
debug: false

# Plugin version info
version: "1.0.0"

# Database settings (future expansion)
database:
  enabled: false
  type: "sqlite"
  
# Trade system settings
trades:
  auto-save: true
  save-interval: 300 # seconds
  backup-trades: true
  max-trades-per-gui: 54
  
# Performance settings
performance:
  cache-items: true
  cache-size: 1000
  async-operations: true
  
# Integration settings
integration:
  proitems: true
  vault: false
  placeholderapi: false

# Trade System Messages
messages:
  prefix: "<gray>[<aqua>ProTrades</aqua>]</gray> "
  trade-created: "<green>Trade <yellow>%trade%</yellow> created successfully!"
  config-saved: "<green>Configuration saved successfully!"
  no-permission: "<red>You don't have permission to use this command."
  
# NBT Configuration
nbt:
  key: "protrades:id"
  namespace-prefix: "protrades"
  
# GUI Configuration
gui:
  default-title: "&1&lProTrades Shop"
  default-rows: 6
  fill-empty-slots: true
  fill-material: "GRAY_STAINED_GLASS_PANE"
  
# Example Configuration
examples:
  create-default-trades: true