# Advanced Trading Templates
# For experienced players seeking powerful combinations

legendary_weapon_fusion:
  name: "Legendary Weapon Fusion"
  description: "Combine legendary weapons for ultimate power"
  category: "advanced"
  enabled: true
  inputs:
    legendary_sword:
      type: "itemx"
      item: "legendary_sword"
      amount: 1
    flaming_blade:
      type: "itemx"
      item: "flaming_blade"
      amount: 1
    frost_blade:
      type: "itemx"
      item: "frost_blade"
      amount: 1
    nether_star:
      type: "regular"
      item: "NETHER_STAR"
      amount: 3
  output:
    type: "itemx"
    item: "thunder_hammer"
    amount: 1
  metadata:
    difficulty: "extreme"
    required_level: 10
    trade_limit: 1
    cooldown: 3600

complete_armor_set:
  name: "Complete Dragon Armor Set"
  description: "Get the full dragon armor set"
  category: "advanced"
  enabled: true
  inputs:
    dragon_helmet:
      type: "itemx"
      item: "dragon_helmet"
      amount: 1
    netherite_chestplate:
      type: "regular"
      item: "NETHERITE_CHESTPLATE"
      amount: 1
    netherite_leggings:
      type: "regular"
      item: "NETHERITE_LEGGINGS"
      amount: 1
    netherite_boots:
      type: "regular"
      item: "NETHERITE_BOOTS"
      amount: 1
    dragon_egg:
      type: "regular"
      item: "DRAGON_EGG"
      amount: 1
  output:
    type: "itemx"
    item: "dragon_chestplate"
    amount: 1
  metadata:
    difficulty: "legendary"
    required_level: 15
    trade_limit: 1
    cooldown: 7200

master_tool_collection:
  name: "Master Tool Collection"
  description: "Trade for the complete master tool set"
  category: "advanced"
  enabled: true
  inputs:
    miners_pickaxe:
      type: "itemx"
      item: "miners_pickaxe"
      amount: 1
    forest_axe:
      type: "itemx"
      item: "forest_axe"
      amount: 1
    beacon:
      type: "regular"
      item: "BEACON"
      amount: 1
    netherite_block:
      type: "regular"
      item: "NETHERITE_BLOCK"
      amount: 5
  output:
    type: "itemx"
    item: "excavator_shovel"
    amount: 1
  metadata:
    difficulty: "hard"
    required_level: 8
    trade_limit: 2
    cooldown: 1800

magical_artifact_trade:
  name: "Magical Artifact Trade"
  description: "Exchange for powerful magical artifacts"
  category: "advanced"
  enabled: true
  inputs:
    teleport_pearl:
      type: "itemx"
      item: "teleport_pearl"
      amount: 5
    healing_potion:
      type: "itemx"
      item: "healing_potion"
      amount: 10
    end_crystal:
      type: "regular"
      item: "END_CRYSTAL"
      amount: 4
    totem_of_undying:
      type: "regular"
      item: "TOTEM_OF_UNDYING"
      amount: 3
  output:
    type: "itemx"
    item: "mana_crystal"
    amount: 2
  metadata:
    difficulty: "extreme"
    required_level: 12
    trade_limit: 3
    cooldown: 2400

ultimate_utility_trade:
  name: "Ultimate Utility Trade"
  description: "Get the best utility items"
  category: "advanced"
  enabled: true
  inputs:
    mana_crystal:
      type: "itemx"
      item: "mana_crystal"
      amount: 3
    lucky_coin:
      type: "itemx"
      item: "lucky_coin"
      amount: 2
    shulker_box:
      type: "regular"
      item: "SHULKER_BOX"
      amount: 8
    bundle:
      type: "regular"
      item: "BUNDLE"
      amount: 1
  output:
    type: "itemx"
    item: "void_bag"
    amount: 1
  metadata:
    difficulty: "legendary"
    required_level: 20
    trade_limit: 1
    cooldown: 10800