# Endgame Trading Templates
# Ultimate trades for veteran players

ultimate_ascension:
  name: "Ultimate Ascension Trade"
  description: "Transcend to ultimate power"
  category: "endgame"
  enabled: true
  inputs:
    thunder_hammer:
      type: "itemx"
      item: "thunder_hammer"
      amount: 1
    dragon_chestplate:
      type: "itemx"
      item: "dragon_chestplate"
      amount: 1
    excavator_shovel:
      type: "itemx"
      item: "excavator_shovel"
      amount: 1
    void_bag:
      type: "itemx"
      item: "void_bag"
      amount: 1
    mana_crystal:
      type: "itemx"
      item: "mana_crystal"
      amount: 10
    dragon_egg:
      type: "regular"
      item: "DRAGON_EGG"
      amount: 5
    nether_star:
      type: "regular"
      item: "NETHER_STAR"
      amount: 64
  output:
    type: "itemx"
    item: "legendary_sword"
    amount: 1
    properties:
      ultimate: true
      ascended: true
      power_level: 1000
  metadata:
    difficulty: "mythic"
    required_level: 50
    trade_limit: 1
    cooldown: 86400
    special: "once_per_player"

perfect_equipment_set:
  name: "Perfect Equipment Set"
  description: "The ultimate equipment collection"
  category: "endgame"
  enabled: true
  inputs:
    legendary_sword:
      type: "itemx"
      item: "legendary_sword"
      amount: 1
    flaming_blade:
      type: "itemx"
      item: "flaming_blade"
      amount: 1
    frost_blade:
      type: "itemx"
      item: "frost_blade"
      amount: 1
    dragon_helmet:
      type: "itemx"
      item: "dragon_helmet"
      amount: 1
    beacon:
      type: "regular"
      item: "BEACON"
      amount: 3
    enchanted_golden_apple:
      type: "regular"
      item: "ENCHANTED_GOLDEN_APPLE"
      amount: 32
  output:
    type: "itemx"
    item: "dragon_leggings"
    amount: 1
  metadata:
    difficulty: "legendary"
    required_level: 25
    trade_limit: 1
    cooldown: 21600

master_collection_trade:
  name: "Master Collection Trade"
  description: "Trade complete collections for ultimate rewards"
  category: "endgame"
  enabled: true
  inputs:
    miners_pickaxe:
      type: "itemx"
      item: "miners_pickaxe"
      amount: 1
    forest_axe:
      type: "itemx"
      item: "forest_axe"
      amount: 1
    excavator_shovel:
      type: "itemx"
      item: "excavator_shovel"
      amount: 1
    farmers_hoe:
      type: "itemx"
      item: "farmers_hoe"
      amount: 1
    netherite_block:
      type: "regular"
      item: "NETHERITE_BLOCK"
      amount: 20
  output:
    type: "itemx"
    item: "dragon_boots"
    amount: 1
  metadata:
    difficulty: "extreme"
    required_level: 18
    trade_limit: 1
    cooldown: 14400

transcendent_power:
  name: "Transcendent Power Trade"
  description: "Unlock transcendent abilities"
  category: "endgame"
  enabled: false  # Admin only
  inputs:
    dragon_helmet:
      type: "itemx"
      item: "dragon_helmet"
      amount: 1
    dragon_chestplate:
      type: "itemx"
      item: "dragon_chestplate"
      amount: 1
    dragon_leggings:
      type: "itemx"
      item: "dragon_leggings"
      amount: 1
    dragon_boots:
      type: "itemx"
      item: "dragon_boots"
      amount: 1
    thunder_hammer:
      type: "itemx"
      item: "thunder_hammer"
      amount: 1
    void_bag:
      type: "itemx"
      item: "void_bag"
      amount: 1
    mana_crystal:
      type: "itemx"
      item: "mana_crystal"
      amount: 50
    dragon_egg:
      type: "regular"
      item: "DRAGON_EGG"
      amount: 10
  output:
    type: "itemx"
    item: "teleport_pearl"
    amount: 100
    properties:
      transcendent: true
      unlimited_use: true
      admin_power: true
  metadata:
    difficulty: "transcendent"
    required_level: 100
    trade_limit: 1
    cooldown: 604800
    special: "admin_approval_required"

infinite_resources:
  name: "Infinite Resources Trade"
  description: "Trade for infinite resource generation"
  category: "endgame"
  enabled: true
  inputs:
    teleport_pearl:
      type: "itemx"
      item: "teleport_pearl"
      amount: 50
    healing_potion:
      type: "itemx"
      item: "healing_potion"
      amount: 64
    mana_crystal:
      type: "itemx"
      item: "mana_crystal"
      amount: 25
    lucky_coin:
      type: "itemx"
      item: "lucky_coin"
      amount: 10
    shulker_box:
      type: "regular"
      item: "SHULKER_BOX"
      amount: 27
    beacon:
      type: "regular"
      item: "BEACON"
      amount: 5
  output:
    type: "itemx"
    item: "farmers_hoe"
    amount: 1
  metadata:
    difficulty: "mythic"
    required_level: 35
    trade_limit: 2
    cooldown: 43200