# Starter Trading Templates
# Perfect for new players starting their trading journey

basic_weapon_upgrade:
  name: "Basic Weapon Upgrade"
  description: "Trade regular weapons for legendary ones"
  category: "starter"
  enabled: true
  inputs:
    diamond_sword:
      type: "regular"
      item: "DIAMOND_SWORD"
      amount: 1
    emeralds:
      type: "regular"
      item: "EMERALD"
      amount: 8
    experience:
      type: "regular"
      item: "EXPERIENCE_BOTTLE"
      amount: 5
  output:
    type: "itemx"
    item: "legendary_sword"
    amount: 1
  metadata:
    difficulty: "easy"
    required_level: 1
    trade_limit: 3
    cooldown: 600

armor_crafting:
  name: "Dragon Armor Crafting"
  description: "Craft powerful dragon armor pieces"
  category: "starter"
  enabled: true
  inputs:
    netherite_helmet:
      type: "regular"
      item: "NETHERITE_HELMET"
      amount: 1
    dragon_breath:
      type: "regular"
      item: "DRAGON_BREATH"
      amount: 5
    netherite_ingot:
      type: "regular"
      item: "NETHERITE_INGOT"
      amount: 2
  output:
    type: "itemx"
    item: "dragon_helmet"
    amount: 1
  metadata:
    difficulty: "medium"
    required_level: 3
    trade_limit: 1
    cooldown: 1200

tool_enhancement:
  name: "Master Tool Creation"
  description: "Transform regular tools into master tools"
  category: "starter"
  enabled: true
  inputs:
    netherite_pickaxe:
      type: "regular"
      item: "NETHERITE_PICKAXE"
      amount: 1
    diamonds:
      type: "regular"
      item: "DIAMOND"
      amount: 16
    ancient_debris:
      type: "regular"
      item: "ANCIENT_DEBRIS"
      amount: 4
  output:
    type: "itemx"
    item: "miners_pickaxe"
    amount: 1
  metadata:
    difficulty: "medium"
    required_level: 2
    trade_limit: 2
    cooldown: 900

magical_item_trade:
  name: "Magical Item Exchange"
  description: "Trade for useful magical items"
  category: "starter"
  enabled: true
  inputs:
    ender_pearl:
      type: "regular"
      item: "ENDER_PEARL"
      amount: 8
    amethyst_shard:
      type: "regular"
      item: "AMETHYST_SHARD"
      amount: 16
    gold_ingot:
      type: "regular"
      item: "GOLD_INGOT"
      amount: 12
  output:
    type: "itemx"
    item: "teleport_pearl"
    amount: 3
  metadata:
    difficulty: "easy"
    required_level: 1
    trade_limit: 5
    cooldown: 300

healing_supplies:
  name: "Healing Supplies Trade"
  description: "Get powerful healing potions"
  category: "starter"
  enabled: true
  inputs:
    potion:
      type: "regular"
      item: "POTION"
      amount: 8
    glistering_melon:
      type: "regular"
      item: "GLISTERING_MELON_SLICE"
      amount: 16
    golden_apple:
      type: "regular"
      item: "GOLDEN_APPLE"
      amount: 4
  output:
    type: "itemx"
    item: "healing_potion"
    amount: 6
  metadata:
    difficulty: "easy"
    required_level: 1
    trade_limit: 10
    cooldown: 150